import { z } from "zod";

// ── Reusable field validators ───────────────────────────────────────────────
const requiredString = z.string().min(1, "This field is required");
const optionalString = z.string().optional();
const requiredNumber = z.number().min(1, "Required").max(5, "Max 5");
const optionalNumber = z.number().min(1).max(5).optional();
const optionalScore = z.number().min(0).max(5).optional();
const optionalBoolean = z.boolean().optional();
const optionalStringArray = z.array(z.string()).default([]);
const requiredBoolean = z.boolean();

// ── IEDS Matrix sub-schema ──────────────────────────────────────────────────
const matrixRowSchema = z.object({
  economic_impact: z.number().min(0).max(10).default(5),
  feasibility: z.number().min(0).max(10).default(5),
  identity_alignment: z.number().min(0).max(10).default(5),
  systems_leverage: z.number().min(0).max(10).default(5),
  risk_return: z.number().min(0).max(10).default(5),
  inclusivity: z.number().min(0).max(10).default(5),
  sustainability: z.number().min(0).max(10).default(5),
});

const iedsMatrixSchema = z.object({
  heds: matrixRowSchema,
  gems: matrixRowSchema,
  ifes: matrixRowSchema,
  ieds: matrixRowSchema,
});

// ── Main Survey Schema ──────────────────────────────────────────────────────
export const surveySchema = z.object({
  // ═══ SECTION 0: WELCOME & ORIENTATION ══
  q0_1_ready: optionalString,
  q0_2_ecosystem_understanding: optionalString,
  q0_3_systems_thinking_value: optionalScore,
  q0_4_cld_understanding: optionalScore,
  q0_5_feedback_loops_understanding: optionalScore,
  q0_6_leverage_points_understanding: optionalScore,

  // ═══ SECTION 1: PRIVACY & CONSENT ═══
  q1_1_consent_participate: optionalBoolean,
  q1_2_consent_anonymize: optionalBoolean,
  q1_3_consent_email_copy: optionalBoolean,
  q1_4_consent_voluntary: optionalBoolean,

  // ═══ SECTION 2: DEMOGRAPHICS ═══
  demo_name: optionalString,
  demo_email: z.string().email("Valid email required").optional(),
  demo_organization: optionalString,
  demo_position: optionalString,
  demo_province: requiredString,
  demo_category: requiredString,
  demo_expertise: z.array(z.string()).min(1, "Select at least one area of expertise"),

  // ═══ SECTION 3: BEIE FRAMEWORK & SYSTEMS THINKING ═══
  q3_1_beie_video_understanding: optionalScore,
  q3_2_systems_reframing_accuracy: optionalScore,
  q3_3_sector_to_ecosystem_shift: optionalScore,
  q3_4_beie_framework_clarity: optionalScore,
  q3_5_operating_systems_understanding: optionalScore,
  q3_6_five_clusters_understanding: optionalScore,
  q3_7_investment_development_loop: optionalString,
  q3_8_governance_investor_loop: optionalString,

  // ═══ SECTION 4: CLUSTER 1 - FOUNDATIONS ═══
  q4_1_foundations_banner_understanding: optionalScore,
  q4_2_tragedy_commons_accuracy: optionalString,
  q4_3_tragedy_followup: optionalString,
  q4_4_climate_impact: optionalScore,
  q4_5_climate_likelihood: optionalScore,
  q4_6_pestalotiopsis_impact: optionalScore,
  q4_7_pestalotiopsis_likelihood: optionalScore,
  q4_8_postharvest_impact: optionalScore,
  q4_9_postharvest_likelihood: optionalScore,
  q4_10_poverty_impact: optionalScore,
  q4_11_poverty_likelihood: optionalScore,
  q4_12_limits_growth_accuracy: optionalString,
  q4_13_limits_followup: optionalString,

  // ═══ SECTION 5: CLUSTER 2 - TRANSFORMERS ═══
  q5_1_transformers_banner_understanding: optionalScore,
  q5_2_halal_advantage_understanding: optionalScore,
  q5_3_farm_to_market_understanding: optionalScore,
  q5_4_economic_zones_understanding: optionalScore,
  q5_5_growth_underinvestment_accuracy: optionalString,
  q5_6_growth_underinvestment_followup: optionalString,
  q5_7_halal_cert_impact: optionalScore,
  q5_8_halal_cert_likelihood: optionalScore,
  q5_9_skills_mismatch_impact: optionalScore,
  q5_10_skills_mismatch_likelihood: optionalScore,
  q5_11_global_halal_impact: optionalScore,
  q5_12_global_halal_likelihood: optionalScore,
  q5_13_uae_corridor_impact: optionalScore,
  q5_14_uae_corridor_likelihood: optionalScore,
  q5_15_competition_impact: optionalScore,
  q5_16_competition_likelihood: optionalScore,

  // ═══ SECTION 6: CLUSTER 3 - ENABLERS ═══
  q6_1_enablers_banner_understanding: optionalScore,
  q6_2_skills_gap_understanding: optionalScore,
  q6_3_enabling_grid_understanding: optionalScore,
  q6_4_digital_transformation_understanding: optionalScore,
  q6_5_tourism_master_plan_understanding: optionalScore,
  q6_6_tourism_digital_connectivity_understanding: optionalScore,
  q6_7_activating_enablers_understanding: optionalScore,
  q6_8_limits_growth_enablers_accuracy: optionalString,
  q6_9_limits_growth_enablers_followup: optionalString,
  q6_10_youth_pop_impact: optionalScore,
  q6_11_youth_pop_likelihood: optionalScore,
  q6_12_renewable_energy_impact: optionalScore,
  q6_13_renewable_energy_likelihood: optionalScore,
  q6_14_polloc_impact: optionalScore,
  q6_15_polloc_likelihood: optionalScore,
  q6_16_infra_deficits_impact: optionalScore,
  q6_17_infra_deficits_likelihood: optionalScore,
  q6_18_literacy_impact: optionalScore,
  q6_19_literacy_likelihood: optionalScore,
  q6_20_skills_mismatch_impact: optionalScore,
  q6_21_skills_mismatch_likelihood: optionalScore,
  q6_22_tech_adoption_impact: optionalScore,
  q6_23_tech_adoption_likelihood: optionalScore,
  q6_24_renewable_invest_impact: optionalScore,
  q6_25_renewable_invest_likelihood: optionalScore,
  q6_26_tourism_potential_impact: optionalScore,
  q6_27_tourism_potential_likelihood: optionalScore,
  q6_28_political_transition_impact: optionalScore,
  q6_29_political_transition_likelihood: optionalScore,
  q6_30_cost_overruns_impact: optionalScore,
  q6_31_cost_overruns_likelihood: optionalScore,
  q6_32_natl_coord_impact: optionalScore,
  q6_33_natl_coord_likelihood: optionalScore,
  q6_34_shifting_burden: optionalString,
  q6_35_shifting_followup: optionalString,
  q6_36_growth_underinvest: optionalString,
  q6_37_growth_followup: optionalString,

  // ═══ SECTION 7: CLUSTER 4 - CONNECTORS ═══
  q7_1_connectors_banner_understanding: optionalScore,
  q7_2_connectivity_capital_understanding: optionalScore,
  q7_3_integrating_zones_understanding: optionalScore,
  q7_4_provincial_nodes_understanding: optionalScore,
  q7_5_trapped_value_understanding: optionalScore,
  q7_6_revitalizing_maritime_understanding: optionalScore,
  q7_7_shattering_isolation_understanding: optionalScore,
  q7_8_basilan_tawitawi_understanding: optionalScore,
  q7_9_global_integration_understanding: optionalScore,
  q7_10_uae_gcc_understanding: optionalScore,
  q7_11_bimpeaga_map_understanding: optionalScore,
  q7_12_success_successful_accuracy: optionalString,
  q7_13_success_successful_followup: optionalString,
  q7_14_bimpeaga_loc_impact: optionalScore,
  q7_15_bimpeaga_loc_likelihood: optionalScore,
  q7_16_domestic_halal_impact: optionalScore,
  q7_17_domestic_halal_likelihood: optionalScore,
  q7_18_polloc_impact: optionalScore,
  q7_19_polloc_likelihood: optionalScore,
  q7_20_islamic_finance_impact: optionalScore,
  q7_21_islamic_finance_likelihood: optionalScore,
  q7_22_infra_deficits_impact: optionalScore,
  q7_23_infra_deficits_likelihood: optionalScore,
  q7_24_fragmented_policy_impact: optionalScore,
  q7_25_fragmented_policy_likelihood: optionalScore,
  q7_26_market_linkages_impact: optionalScore,
  q7_27_market_linkages_likelihood: optionalScore,
  q7_28_tech_adoption_impact: optionalScore,
  q7_29_tech_adoption_likelihood: optionalScore,
  q7_30_asean_halal_impact: optionalScore,
  q7_31_asean_halal_likelihood: optionalScore,
  q7_32_bimpeaga_integration_impact: optionalScore,
  q7_33_bimpeaga_integration_likelihood: optionalScore,
  q7_34_uae_corridor_impact: optionalScore,
  q7_35_uae_corridor_likelihood: optionalScore,
  q7_36_tourism_potential_impact: optionalScore,
  q7_37_tourism_potential_likelihood: optionalScore,
  q7_38_halal_competition_impact: optionalScore,
  q7_39_halal_competition_likelihood: optionalScore,
  q7_40_security_incidents_impact: optionalScore,
  q7_41_security_incidents_likelihood: optionalScore,
  q7_42_price_volatility_impact: optionalScore,
  q7_43_price_volatility_likelihood: optionalScore,
  q7_44_natl_coord_impact: optionalScore,
  q7_45_natl_coord_likelihood: optionalScore,
  q7_46_escalation: optionalString,
  q7_47_escalation_followup: optionalString,
  q7_48_limits_growth: optionalString,
  q7_49_limits_followup: optionalString,

  // ═══ SECTION 8: CLUSTER 5 - FINANCIERS ═══
  q8_1_financiers_banner_understanding: optionalScore,
  q8_2_capital_bloodstream_understanding: optionalScore,
  q8_3_islamic_finance_roadmap_understanding: optionalScore,
  q8_4_shifting_burden_financiers_accuracy: optionalString,
  q8_5_shifting_burden_financiers_followup: optionalString,
  q8_6_domestic_halal_impact: optionalScore,
  q8_7_domestic_halal_likelihood: optionalScore,
  q8_8_youth_pop_impact: optionalScore,
  q8_9_youth_pop_likelihood: optionalScore,
  q8_10_policy_recognition_impact: optionalScore,
  q8_11_policy_recognition_likelihood: optionalScore,
  q8_12_islamic_finance_fw_impact: optionalScore,
  q8_13_islamic_finance_fw_likelihood: optionalScore,
  q8_14_peace_dividend_impact: optionalScore,
  q8_15_peace_dividend_likelihood: optionalScore,
  q8_16_infra_deficits_impact: optionalScore,
  q8_17_infra_deficits_likelihood: optionalScore,
  q8_18_literacy_impact: optionalScore,
  q8_19_literacy_likelihood: optionalScore,
  q8_20_financial_penetration_impact: optionalScore,
  q8_21_financial_penetration_likelihood: optionalScore,
  q8_22_fragmented_policy_impact: optionalScore,
  q8_23_fragmented_policy_likelihood: optionalScore,
  q8_24_skills_mismatch_impact: optionalScore,
  q8_25_skills_mismatch_likelihood: optionalScore,
  q8_26_global_halal_impact: optionalScore,
  q8_27_global_halal_likelihood: optionalScore,
  q8_28_renewable_invest_impact: optionalScore,
  q8_29_renewable_invest_likelihood: optionalScore,
  q8_30_asean_halal_impact: optionalScore,
  q8_31_asean_halal_likelihood: optionalScore,
  q8_32_islamic_ecosystem_impact: optionalScore,
  q8_33_islamic_ecosystem_likelihood: optionalScore,
  q8_34_uae_corridor_impact: optionalScore,
  q8_35_uae_corridor_likelihood: optionalScore,
  q8_36_halal_competition_impact: optionalScore,
  q8_37_halal_competition_likelihood: optionalScore,
  q8_38_halal_standards_impact: optionalScore,
  q8_39_halal_standards_likelihood: optionalScore,
  q8_40_security_incidents_impact: optionalScore,
  q8_41_security_incidents_likelihood: optionalScore,
  q8_42_political_transition_impact: optionalScore,
  q8_43_political_transition_likelihood: optionalScore,
  q8_44_big_man: optionalString,
  q8_45_big_man_followup: optionalString,
  q8_46_shifting_burden: optionalString,
  q8_47_shifting_followup: optionalString,

  // ═══ SECTION 9: OPERATING SYSTEMS ═══
  q9_1_os_banner_understanding: optionalScore,
  q9_2_moral_governance_derisk_understanding: optionalScore,
  q9_3_regulatory_architecture_understanding: optionalScore,
  q9_4_jmc_2026_01_understanding: optionalScore,
  q9_5_fixes_fail_os_accuracy: optionalString,
  q9_6_fixes_fail_os_followup: optionalString,
  q9_7_big_man_archetype_accuracy: optionalString,
  q9_8_big_man_archetype_followup: optionalString,
  q9_9_policy_recommendations_stakeholders_understanding: optionalScore,
  q9_10_policy_recommendations_activating_understanding: optionalScore,
  q9_11_policy_recognition_impact: optionalScore,
  q9_12_policy_recognition_likelihood: optionalScore,
  q9_13_islamic_finance_impact: optionalScore,
  q9_14_islamic_finance_likelihood: optionalScore,
  q9_15_cultural_heritage_impact: optionalScore,
  q9_16_cultural_heritage_likelihood: optionalScore,
  q9_17_peace_dividend_impact: optionalScore,
  q9_18_peace_dividend_likelihood: optionalScore,
  q9_19_literacy_impact: optionalScore,
  q9_20_literacy_likelihood: optionalScore,
  q9_21_fragmented_policy_impact: optionalScore,
  q9_22_fragmented_policy_likelihood: optionalScore,
  q9_23_underspending_impact: optionalScore,
  q9_24_underspending_likelihood: optionalScore,
  q9_25_carbon_markets_impact: optionalScore,
  q9_26_carbon_markets_likelihood: optionalScore,
  q9_27_pes_impact: optionalScore,
  q9_28_pes_likelihood: optionalScore,
  q9_29_postconflict_impact: optionalScore,
  q9_30_postconflict_likelihood: optionalScore,
  q9_31_forestry_code_impact: optionalScore,
  q9_32_forestry_code_likelihood: optionalScore,
  q9_33_security_incidents_impact: optionalScore,
  q9_34_security_incidents_likelihood: optionalScore,
  q9_35_political_transition_impact: optionalScore,
  q9_36_political_transition_likelihood: optionalScore,
  q9_37_fragmented_agency_impact: optionalScore,
  q9_38_fragmented_agency_likelihood: optionalScore,
  q9_39_investment_loop: optionalString,
  q9_40_investment_loop_followup: optionalString,
  q9_41_governance_loop: optionalString,
  q9_42_governance_loop_followup: optionalString,

  // ═══ SECTION 10: IEDS & 3-PHASE PLAN ═══
  q10_1_strategic_options_video_understanding: optionalScore,
  q10_2_leverage_points_identification_understanding: optionalScore,
  q10_3_activating_leverage_points_understanding: optionalScore,
  q10_4_leverage_capacity_traps_understanding: optionalScore,
  q10_5_leverage_governance_traps_understanding: optionalScore,
  q10_6_architecting_collaborative_governance_understanding: optionalScore,
  q10_7_archetypes_leverage_points_understanding: optionalScore,
  q10_8_strategic_options_ranking: optionalString,
  q10_9_ieds_execution_engine_understanding: optionalScore,
  q10_10_ieds_preference: optionalString,
  q10_11_sequence_a_priority: optionalScore,
  q10_12_sequence_b_priority: optionalScore,
  q10_13_sequence_c_priority: optionalScore,
  q10_14_sequencing_logic: optionalString,
  q10_15_risk_mitigation: optionalString,
  q10_16_outcomes_achievable: optionalScore,
  q10_matrix: iedsMatrixSchema,

  // ═══ SECTION 11: METRICS ARCHITECTURE ═══
  q11_1_metrics_architecture_understanding: optionalScore,
  q11_2_drifting_goals_accuracy: optionalString,
  q11_3_drifting_goals_followup: optionalString,
  q11_4_calibration_appropriate: optionalString,
  q11_5_governance_kpi_importance: optionalScore,
  q11_6_resilience_kpi_importance: optionalScore,
  q11_7_inclusivity_kpi_importance: optionalScore,
  q11_8_peace_kpi_importance: optionalScore,
  q11_9_cluster_kpi_sufficient: optionalString,
  q11_10_benchmark_priority: optionalString,

  // ═══ SECTION 12: BALANCED SCORECARD ══
  q12_1_bsc_video_understanding: optionalScore,
  q12_2_bsc_intangibles_understanding: optionalScore,
  q12_3_bsc_economic_outcomes_understanding: optionalScore,
  q12_4_vision_understanding: optionalScore,
  q12_5_learning_growth_alignment: optionalScore,
  q12_6_internal_process_alignment: optionalScore,
  q12_7_stakeholder_alignment: optionalScore,
  q12_8_financial_alignment: optionalScore,
  q12_9_strongest_pathway: optionalString,
  q12_10_vision_clarity: optionalScore,
  q12_11_vision_achievable: optionalScore,
  q12_12_mission_alignment: optionalScore,
  q12_13_bsc_useful: optionalScore,
  q12_14_adaptive_frequency: optionalString,

  // ══ SECTION 13: PRIORITY ACTIONS & BUDGET ═══
  q13_1_capital_deployment_understanding: optionalScore,
  q13_2_funding_mix_fair: optionalScore,
  q13_3_targets_realistic: optionalScore,
  q13_4_high_risk_concern: optionalScore,
  q13_5_medium_risk_concern: optionalScore,
  q13_6_low_risk_concern: optionalScore,
  q13_7_budget_priority_phase: optionalString,
  q13_8_budget_priority_cluster: optionalString,
  q13_9_blended_finance_opinion: optionalString,

  // ═══ SECTION 14: ACCESS TO RESOURCES & ENGAGEMENTS ═══
  q14_1_engagement_type: optionalStringArray,
  q14_2_contact_method: optionalString,
  q14_3_timing: optionalString,
  q14_4_role_contribution: optionalString,
  q14_5_additional_comments: optionalString,

  // ═══ SECTION 15: REVIEW & SUBMIT ═══
  q15_1_confirm_accurate: optionalBoolean,
  q15_2_consent_anonymous_use: optionalBoolean,
  q15_3_consent_voluntary: optionalBoolean,
  q15_4_ready_to_submit: optionalBoolean,
  q15_5_overall_assessment: optionalScore,
  q15_6_strongest_aspects: optionalString,
  q15_7_weakest_aspects: optionalString,
  q15_8_recommend: optionalString,
  q15_9_modifications: optionalString,
  q15_10_final_comments: optionalString,
});

export type SurveySchemaType = z.infer<typeof surveySchema>;
